### ISSUE TITLE
ReactNative stuck at Running script '[CP] Prepare Artifacts'

### ISSUE THREAD

**Issue by rborn** [invertase/firestore-ios-sdk-frameworks#10]
It seems that when you add the precompiled sdk the above step freezes.

Might be a cocoapods issue, but I wonder fi you have any idea? 

In the `Pods/Target Support Files/Pods-{target}-artifacts.sh` the below line will freeze (no idea why 😅)

```
ARTIFACT_LIST_FILE="${BUILT_PRODUCTS_DIR}/cocoapods-artifacts-${CONFIGURATION}.txt"
cat > $ARTIFACT_LIST_FILE
```

OSX Mojave
Xcode 11.2.1
Latest RNFirebase.
RN: 0.61.4

Thank you 😻

**Comment by mikehardy** [comment]
This doesn't happen to me but I'm on up to date Xcode, I wonder if that's a thing?

**Comment by rborn** [comment]
I'm afraid to upgrade 😅

**Comment by mikehardy** [comment]
RIp the bandaid off @rborn  ;-)
But have the first air ready haha

**Comment by tzappia** [comment]
I had the same issue with a Cordova/AngularJS project. I think it's a CocoaPods issue. It was happening consistently with pod version 1.9.3. I upgraded to their latest beta, 1.10.0.beta.2 with `sudo gem install cocoapods --pre` and the issue was solved. One of their scripts was doing `cat > $ARTIFACT_LIST_FILE` and cat with no arguments would just sit there.

**Comment by rborn** [comment]
@tzappia thnx for the update, will test later this week and let you know

**Comment by rborn** [comment]
@mikehardy @tzappia finally upgraded xcode and cocoapods to 1.10.0.rc.1 and all goes smooth. Thanks for all the help 😻

**Comment by luan03** [comment]
`sudo gem install cocoapods` solved my problem.

Cheers guys.
