### ISSUE TITLE
Mac OS version

### ISSUE THREAD

**Issue by TimWhiting** [invertase/firestore-ios-sdk-frameworks#11]
Would love a Mac OS version of this.

**Comment by Salakar** [comment]
As far as I can tell only a Catalyst version of this is shipped with the iOS SDK which is why it's not working out the box: https://github.com/invertase/firestore-ios-sdk-frameworks/tree/master/FirebaseFirestore/FirebaseFirestore.xcframework

Though this should mostly be compatible (?), I just need to spend some time looking into it.

**Comment by mikehardy** [comment]
I believe the upstream distribution would need to include a macOS build, since this is effectively just a repackaging of it? Is there any action we can actually take here?

**Comment by Salakar** [comment]
From the 7.4.0 release notes: 

> Zip distribution now includes community supported macOS and tvOS libraries. 

So I believe this should now work for version 7.4 and later 🎉 I can see the macos frameworks now in this repository

**Comment by Salakar** [comment]
Confirmed working in https://github.com/FirebaseExtended/flutterfire/pull/4698

Almost 8 minutes build time reduction 🎉
