### ISSUE TITLE
Xcode 12.4 Module 'FirebaseFirestore' not found

### ISSUE THREAD

**Issue by janarieldev** [invertase/firestore-ios-sdk-frameworks#28]
Hi, I'm trying to build my iOS app developed on ionic. When building on Xcode, I get the error.

**Screenshots:**
![image](https://user-images.githubusercontent.com/56248336/110869776-162ca880-8306-11eb-879f-0d70abdedc50.png)
![image](https://user-images.githubusercontent.com/56248336/110869787-1c228980-8306-11eb-8d51-389dcc4f145c.png)

**As for my Podfile, here is the content:**
![image](https://user-images.githubusercontent.com/56248336/110869845-3f4d3900-8306-11eb-96a2-8c26b5ea440c.png)

Also, if I build with `$ ionic cordova build ios --prod --release`. I get this error
```
The following build commands failed:
	CompileC /Users/jans/Library/Developer/Xcode/DerivedData/Jan-bbcnrsrdkhulxxgtcbuzbbwmxmej/Build/Intermediates.noindex/Jan.build/Release-iphonesimulator/Jan.build/Objects-normal/arm64/AppDelegate+FirebasePlugin.o Jan/Plugins/cordova-plugin-firebasex/AppDelegate+FirebasePlugin.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65
[ERROR] An error occurred while running subprocess cordova.
```

**Comment by mikehardy** [comment]
Hi there!

No idea why the import isn't working, that's quite strange. Usually when things like that happen it is from opening it via the .xcproject instead of the .xcworkspace but that's just a medium-percentage guess

You have noted the command that failed, but not the actual failure reason (usually up higher in the build log, after the command is issued, there will be details about the problem)

Tangent: I can't imagine using version 6.33 of the firebase-ios-sdk though, is there some reason 7.x.x is not accessible?

**Comment by janarieldev** [comment]
@mikehardy Thanks for replying!

Regarding using 7.x.x version, I tried 7.6.0 and I also encountered the same problem. If it helps, I assume this was auto generated from [cordova-plugin-firebasex](https://github.com/dpa99c/cordova-plugin-firebasex#cordova-cli-builds).

**Comment by mikehardy** [comment]
I'm not sure we will be much help here unfortunately. There is nothing inherently complicated about what these pre-compiled frameworks offer and in a standard Xcode project they should be a drop-in replacement for FirebaseFirestore - with all header / library paths etc working. I have no Cordova reproduction environment so I won't be able to troubleshoot this, all I can say is that it does work in multiple ecosystems (specifically, Flutter and react-native) so it should be possible, but I can't say farther than that.

Maybe someone else with Cordova experience will be able to help but you may have more luck on stackoverflow if there is an active Cordova + firebase community there - this is the first Cordova traffic we've seen here so it's unlikely to get attention without reaching out to other communication platforms

**Comment by garberd23** [comment]
> Hi, I'm trying to build my iOS app developed on ionic. When building on Xcode, I get the error.
> 
> **Screenshots:**
> ![image](https://user-images.githubusercontent.com/56248336/110869776-162ca880-8306-11eb-879f-0d70abdedc50.png)
> ![image](https://user-images.githubusercontent.com/56248336/110869787-1c228980-8306-11eb-8d51-389dcc4f145c.png)
> 
> **As for my Podfile, here is the content:**
> ![image](https://user-images.githubusercontent.com/56248336/110869845-3f4d3900-8306-11eb-96a2-8c26b5ea440c.png)
> 
> Also, if I build with `$ ionic cordova build ios --prod --release`. I get this error
> 
> ```
> The following build commands failed:
> 	CompileC /Users/jans/Library/Developer/Xcode/DerivedData/Jan-bbcnrsrdkhulxxgtcbuzbbwmxmej/Build/Intermediates.noindex/Jan.build/Release-iphonesimulator/Jan.build/Objects-normal/arm64/AppDelegate+FirebasePlugin.o Jan/Plugins/cordova-plugin-firebasex/AppDelegate+FirebasePlugin.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> (1 failure)
> xcodebuild: Command failed with exit code 65
> [ERROR] An error occurred while running subprocess cordova.
> ```

Did you ever solve this issue? How?

**Comment by rafalzawadzki** [comment]
I noticed a similar issue in a React Native project:

<img width="262" alt="Screen Shot 2021-04-19 at 4 05 30 PM" src="https://user-images.githubusercontent.com/10667346/115530796-64817f80-a294-11eb-8ac3-f38b16df5892.png">

It happens only for Release targets. When the pod is removed the builds succeed.

Pod version we use:
> pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '6.30.0'

**Comment by mikehardy** [comment]
Hi there! Not sure why you would use a version from more than a year ago? It may be that some non-forward-compatible changes have leaked in somewhere? For react-native this is *definitely definitely* working in modern versions though. I maintain react-native-firebase which I mention because it carries the implication that I manage the CI integration there and merge PRs (so I define the build steps and watch the builds) and we average more than a build a day, plus my own app which uses this framework, and it all builds cleanly, including for release

**Comment by rafalzawadzki** [comment]
Thanks @mikehardy, we updated to the newest version and this build issue disappeared indeed! 👏
