### ISSUE TITLE
Issue with using 8.4.0

### ISSUE THREAD

**Issue by Gene-Dana** [invertase/firestore-ios-sdk-frameworks#34]
Hi there ! I ran into this issue

![image](https://user-images.githubusercontent.com/45580241/127520701-45b8062f-f00c-4a7f-a404-3de58d43a69e.png)

I solved it by switching to 8.3.0 and thought perhaps it would be useful to share !

**Comment by mikehardy** [comment]
Yes! The firestore dependency here **must match** the one used by everything else.

Note in your Podfile I believe it is possible to specify the version dynamically so they are in sync naturally without maintenance effort. I believe you will like this snippet:

https://github.com/FirebaseExtended/flutterfire/blob/1795261e09a73080703af3609dd198758b4f3032/packages/cloud_firestore/cloud_firestore/example/ios/Podfile#L37-L51

**Comment by Gene-Dana** [comment]
I do like that snippet ! I appreciate it, thanks !!!

**Comment by Gene-Dana** [comment]
Hey there ! just to be certain @mikehardy, I replace this with the code your provided above?

```dart
target 'Runner' do
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '8.3.0'

  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '8.3.0'

```

**Comment by mikehardy** [comment]
Podfiles themselves are code, and code is infinitely variable, so I cannot say 100% that you should do exactly this thing or exactly that thing.

I can say that the '8.3.0' reference will require manual maintenance from you going forward, and the goal of the snippet I posted was to show how to use ruby (the language of Podfiles) to programmatically feel around your apps' directory tree to find the firebase_core ruby config script, and use *it* to get your firebase-ios-sdk version, then use that version in place of `8.3.0` so it's dynamic.

You'll have to experiment in order to make it work exactly, it always takes me a few test/run/fix tries when I'm playing with Podfiles personally but I always get there in the end. Good luck!

**Comment by Gene-Dana** [comment]
I agree with the intention and approach ! Just wanted to make sure I was following your guidance ! thanks
