### ISSUE TITLE
ver 8.4.0 issue

### ISSUE THREAD

**Issue by rolinger** [invertase/firestore-ios-sdk-frameworks#35]
HI, I am installing `Cordova-plugin-firebasex` which pulls this (and other) pods.  But I am getting the following error - its similar to another issue already closed, but it looks slightly different.

```
[!] CocoaPods could not find compatible versions for pod "FirebaseFirestore":
  In Podfile:
    FirebaseFirestore (from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `8.4.0`)

Specs satisfying the `FirebaseFirestore (from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `8.4.0`)` dependency were found, but they required a higher minimum deployment target.
```

Then when I try to install it directly, I get the following:

```
pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '8.4.0' 

zsh: no such file or directory: https://github.com/invertase/firestore-ios-sdk-frameworks.git,
```

How can I resolve this?

**Comment by mikehardy** [comment]
Hi there!

This error message:

> Specs satisfying the `FirebaseFirestore (from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `8.4.0`)` dependency were found, but they required a higher minimum deployment target.

...means exactly what it says. You need to have your Podfile specify a minimum iOS version at least as high as these frameworks in order to use them.

We require these minimum targets:

https://github.com/invertase/firestore-ios-sdk-frameworks/blob/5e2eaf436782e60e49448e2d852f2f171181d2a9/FirebaseFirestore.podspec#L23-L25

For the second error message, I can't say, sorry

**Comment by rolinger** [comment]
@mikehardy - thanks.  I didn't realize it was referring to the iOS version.  I kept thinking it was related an SDK minimum target.  Thanks for explaining.
