### ISSUE TITLE
CI job failing since v9.0.0

### ISSUE THREAD

**Issue by Salakar** [invertase/firestore-ios-sdk-frameworks#49]
Example: https://github.com/invertase/firestore-ios-sdk-frameworks/runs/6357150377?check_suite_focus=true

**Comment by paulb777** [comment]
With 9.0.0 we stopped adding the additional "v" tag: https://github.com/firebase/firebase-ios-sdk/tags

**Comment by mikehardy** [comment]
perfect - from looking at the actions logs it was just a failure to download so I figured it was something like that. Thanks for the hint @paulb777

**Comment by mikehardy** [comment]
@paulb777 you guys have actually gone from having no 'v' to having a 'v' to having no 'v', and I'd left the fallback style in there, so that turned out not to be the thing.

Github used to send HTML documents with redirects in the doc and we were parsing that, it appears they no longer do that and just send a 302 with location header, so I just needed to change how we snagged the actual binary.

Done!
