### ISSUE TITLE
Guidance needed in correlating Firebase pubspec.yaml version & tag 

### ISSUE THREAD

**Issue by glintpursuit** [invertase/firestore-ios-sdk-frameworks#70]

**Comment by glintpursuit** [comment]
How to find out whether Current firebase core version which is 2.4.1 is compatible with tag 10.4.0 ?

**Comment by mikehardy** [comment]
10.4.0 is not compatible with flutter yet, I think, because it appears to also be affected by the new strict requirement in 10.4.0 that you must have an APNS token before trying to get an FCM token (see https://github.com/firebase/firebase-ios-sdk/issues/10679#issuecomment-1402776795)

In general the firebase core version for Flutter is only known to be compatible with the version it specifies. Any time you override it you are responsible for any problems / incompatibilities.

So the only "known compatible" tag to use is either fetched dynamically somehow from firebase core's deps, or by inspection right here: https://github.com/firebase/flutterfire/blob/fd3026a4c281fcd90b7fc9007ae39d226b19a66f/packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb#L3

With respect, I don't think this is actionable here and I *think* I've answered your question with enough information for you to make decisions, so I'll close this

**Comment by glintpursuit** [comment]
Got your point, Thanks @mikehardy for quick response.
