### ISSUE TITLE
SDK Not Supported By Compiler

### ISSUE THREAD

**Issue by julianfalcionelli** [invertase/firestore-ios-sdk-frameworks#83]
Hi there,

I am getting the following errors when using the latest version (10.19.0).

<img width="908" alt="Screenshot 2023-12-07 at 13 25 03" src="https://github.com/invertase/firestore-ios-sdk-frameworks/assets/5782994/cbdb6262-0553-4a16-83f4-84d3d4984493">

I have the latest Flutter / Dart version and the latest Firebase Plugins.

If I don't use this pre-compiled library (and use the default Firebase SDKs), these errors don't happen (but the building time is ridiculous).

Is this related to the XCode versions used to generate this artifact ? 

Best!

**Comment by mikehardy** [comment]
A couple thoughts -

1- I don't believe anything higher than 10.16.0 is supported at the moment because of #79 - you might like #82 to get away from the whole idea of this build optimization hack and use a more industry-standard build-time optimization
2- there is not quite enough version information to go on (what version of macOS + Xcode resulted in that error message?)
3- it looks like at minimum you need to bump your IOS_DEPLOYMENT_TARGET to 12 to use the framework

**Comment by julianfalcionelli** [comment]
@mikehardy updating to the latest Xcode and Mac didn't help, I am going to downgrade Firebase to 10.16.0. Thanks for your help!
